version: "3.9"

services:
  db:
    image: mysql:5.7
    ports:
      - "33061:3306"
    command: --init-file /data/scripts/init.sql
    volumes:
      - ./scripts/:/data/scripts/
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: simple_library
      MYSQL_USER: librarian
      MYSQL_PASSWORD: password